name: manual-event
on:
  workflow_dispatch:
    inputs:
      name:
          description: "Name of the person to greet"
          type: string
          required: true
      greet:
          description: "Type of greet"
          type: string
          required: true
      base64FileContent:
          description: "Base64 File content"
          type: string
          required: true
jobs:
  greet:
    runs-on: "ubuntu-latest"
    steps:
      - name: Decode file content
        run: |
          echo "${{inputs.base64FileContent}}" | base64 --decode > ./decode.txt
      - name: Greet to person
        run: |
          echo "${{inputs.name}} : ${{inputs.greet}}"
      - name: Print decoded file in console
        run: |
          echo "Contents of the file"
          cat ./decode.txt


          