name: Reusable test workflow
on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: sumanmanna134/GithubActions/.github/workflows/res.yaml@main
    with:
      greet_name: 'Suman Manna'
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    
    # uses: sumanmanna134/GithubActions/.github/workflows/res.yaml@main
    # with:
    #   greet_name: 'Suman Manna'