name: Reusable workflow
on:
  workflow_call:
    inputs:
      greet_name:
        description: "To greet the name"
        required: true
        type: string
        
    secrets:
      MY_SECRET:
        required: false
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Echo secret (example usage)
        run: echo "The secret is ${{ secrets.MY_SECRET }}" 
      - name: Run tests
        run: ${{ inputs.greet_name }}
      - name: Print Console
        run: echo ${{github.actor}}



        

    
      
    